### ISSUE TITLE
distribute configmap-sar.yaml to all global regions

### ISSUE THREAD

**Issue by pahud** [pahud/eks-templates#28]
we should `sed` and replace the regoin code before distribute to other regions

https://github.com/pahud/eks-templates/blob/4ea737c5f002c91ff6457e1d7ce1e8496744659a/Makefile#L62-L90

        ApplicationId: arn:aws:serverlessrepo:ap-northeast-1:903779448426:applications/eks-auth-update-hook

**Comment by pahud** [comment]
SAR should be able to share public Application through `us-east-1` so we simply configure it like this then all AWS account from any region with AWS Lambda should be able to pull this app from SAR and spin it up.

https://github.com/pahud/eks-templates/blob/4d000bb31cc527608e1c865848ba6037e3365003/cloudformation/configmap-sar.yaml#L26-L27

**Comment by blontic** [comment]
I get this is how it works for public applications but what if I want a private application that is deployed to a few different regions?

We really need a way to do 
`ApplicationId: !Sub arn:aws:serverlessrepo:${AWS::Region}:903779448426:applications/eks-auth-update-hook `
