### ISSUE TITLE
could not get token: AccessDenied: Access denied

### ISSUE THREAD

**Issue by harryliu123** [pahud/eks-templates#40]
您好
我建立cloud9 利用cloud9建立後續--> VPC--> subnet--> make create-eks-cluster
再來建立EKS config
aws --region us-east-2 eks update-kubeconfig --name eksdemo --role-arn arn:aws:iam::620154271401:role/AmazonEKSAdminRole

Added new context arn:aws:eks:us-east-2:620154271401:cluster/eksdemo to /home/ec2-user/.kube/config

 kubectl get no
could not get token: AccessDenied: Access denied
        status code: 403, request id: cb2eac65-454e-11e9-94f9-37274ff97c3e
could not get token: AccessDenied: Access denied
        status code: 403, request id: cb496037-454e-11e9-bc8f-2bc50b3f4206
could not get token: AccessDenied: Access denied
        status code: 403, request id: cb6610cd-454e-11e9-b779-690a1fef9c13
could not get token: AccessDenied: Access denied
        status code: 403, request id: cb81d5bf-454e-11e9-affe-01d5063ef055
could not get token: AccessDenied: Access denied
        status code: 403, request id: cb9d4c8a-454e-11e9-9dbf-25020ebc0a81
Unable to connect to the server: getting credentials: exec: exit status 1

請問發生甚麼問題呢?

------
$ cat config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <......>
    server: https://792DE6BFF2357E553C643D216C74D05F.yl4.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:620154271401:cluster/eksdemo
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:620154271401:cluster/eksdemo
    user: arn:aws:eks:us-east-2:620154271401:cluster/eksdemo
  name: arn:aws:eks:us-east-2:620154271401:cluster/eksdemo
current-context: arn:aws:eks:us-east-2:620154271401:cluster/eksdemo
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:620154271401:cluster/eksdemo
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - eksdemo
      - -r
      - arn:aws:iam::620154271401:role/AmazonEKSAdminRole
      command: aws-iam-authenticator

**Comment by pahud** [comment]
你需要確保你當前運行AWS CLI的身分，可以assume成AmazonEKSAdminRole

參考test and validate這段說明

https://github.com/pahud/eks-templates#test-and-validate

**Comment by harryliu123** [comment]
謝謝, 在更新AmazonEKSAdminRole 已解決
