### ISSUE TITLE
kubectl get no got "no resource found" 

### ISSUE THREAD

**Issue by harryliu123** [pahud/eks-templates#42]

**Comment by harryliu123** [comment]
您好
解決掉 role問題後要在請您幫忙

 $ aws --region us-east-2 eks update-kubeconfig --name eksdemo --role-arn arn:aws:iam::620154271401:role/AmazonEKSAdminRole
Updated context arn:aws:eks:us-east-2:620154271401:cluster/eksdemo in /home/ec2-user/.kube/config

$ kubectl get po
No resources found.

$ kubectl get node
No resources found.
$ kubectl get service
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.20.0.1   <none>        443/TCP   2h

**Comment by pahud** [comment]
Hi 

I can't help you with the info you provided above. Please make sure your cloudformation stacks are all completed in green state and check if there's any other errors. It seems like your cluster is ready but nodegroup failed to registered to the control plane.

**Comment by harryliu123** [comment]
Thanks for your support
i has succeeded make a EKS
create VPC and subnet before make eks
if you ok, i can summit a some code
