### ISSUE TITLE
CL creates unlimited CL nested stacks 

### ISSUE THREAD

**Issue by olektretiak** [pahud/eks-templates#49]
Hi,

I've tried to use tools you provided, but I've got limit of stacks, Please check the screenshot
![Screen Shot 2019-04-19 at 19 01 42](https://user-images.githubusercontent.com/48690170/56432336-9f333480-62d5-11e9-8f68-1ccde30c23f3.png)

**Comment by pahud** [comment]
@olektretiak thanks feedback

Can you let me know how do you create the cluster? Just `make create-eks-cluster` ? Any parameters?

**Comment by olektretiak** [comment]
> @olektretiak thanks feedback
> 
> Can you let me know how do you create the cluster? Just `make create-eks-cluster` ? Any parameters?

Yes, without any parameters.

**Comment by olektretiak** [comment]
I've fixed the issue by redownload the repo. Sorry for the inconviniance
