### ISSUE TITLE
eks-auth-update-hook could not be found

### ISSUE THREAD

**Issue by olektretiak** [pahud/eks-templates#50]
Could you please help me to resolve the issue. I've updated  the user in the templates  like `arn:aws:serverlessrepo:us-east-1:943038521233:applications/eks-auth-update-hook` and I've got the following issue.
Could you please provide how to setup update-hook?
<img width="1419" alt="Screen Shot 2019-04-22 at 18 45 55" src="https://user-images.githubusercontent.com/48690170/56563231-ccbcfe00-65b3-11e9-8d23-6474cdb79bcb.png">

**Comment by pahud** [comment]
you don't have to configure it as the update-hook is a serverless app in SAR already and anyone should be able to use it. Let me look into this issue.

**Comment by pahud** [comment]
Hi @olektretiak 

which region are you trying to deploy to?

**Comment by olektretiak** [comment]
> Hi @olektretiak
> 
> which region are you trying to deploy to?
Hi @pahud,
Thank you for your replay!
us-east-1

**Comment by pahud** [comment]
Hi @olektretiak 

I was running on another aws account and everything is good.

![image](https://user-images.githubusercontent.com/278432/56629185-1e7e8a80-667f-11e9-8ec9-45b6dc43041b.png)

what I did was creating a `custom.mk` file
``
EKS_ADMIN_ROLE ?= arn:aws:iam::XXXXXXXXXX:role/AmazonEKSAdminRole
REGION ?= us-east-1
SSH_KEY_NAME ?= 'pahud'
VPC_ID ?= vpc-46c1db22
SUBNET1 ?= subnet-01fb6759
SUBNET2 ?= subnet-23c48355
SUBNET3 ?= subnet-f65cc8dc
OnDemandBaseCapacity ?= 1
NodeAutoScalingGroupMinSize ?= 0
NodeAutoScalingGroupDesiredSize ?= 4
NodeAutoScalingGroupMaxSize ?= 5
ASGAutoAssignPublicIp ?= yes
```
and just run `make create-eks-cluster`

the cloudformation stacks should be created with no error.

Can you try again?

**Comment by pahud** [comment]
OH I got it.

![image](https://user-images.githubusercontent.com/278432/56629401-cf852500-667f-11e9-9bde-e7610b9e8554.png)


Did you modify any content of the cloudformatoin yaml file?

I noticed your stack is pointing to `severlessrepo:us-west-1:943018222035:applications/eks-auth-update-hook`, however I already provided my published app here and you don't have to publish your own to SAR(Serverless App Repository).

https://github.com/pahud/eks-templates/blob/d63d625b696d2f675185208d0b936c0747384ecf/cloudformation/configmap-sar.yaml#L27

The source code of `eks-auth-update-hook` is here:
https://github.com/aws-samples/aws-lambda-layer-kubectl/tree/master/samples/update-configmap

You may publish your own to SAR and include your own in your `configmap-sar.yaml` file. You can just `make sam-publish` to publish your own `eks-auth-update-hook` to SAR, but that is another story.

https://github.com/aws-samples/aws-lambda-layer-kubectl/blob/a0ca765804a2aefdb9ce82cfe50c7b7f529add94/samples/update-configmap/Makefile#L76-L82
